export const categoryLevelInsights: Record<number, string> = {
  1: "You experience minimal autistic traits. You likely navigate social interactions, changes in routine, and sensory environments with ease. While you may occasionally encounter moments of discomfort, they are rare and usually manageable without specific coping strategies.",
  2: "You show a low level of autistic traits. Subtle preferences for routine or mild social discomfort may arise, but they likely don't interfere with daily functioning. You may find benefit in simple grounding techniques during overstimulating situations.",
  3: "You demonstrate mild traits that occasionally affect your behavior and comfort levels. You might need extra time in social situations or prefer consistency in your schedule. Understanding your patterns can help you self-advocate effectively.",
  4: "Your results suggest moderate autistic traits. You may find social interactions or sensory inputs draining and prefer structure in your environment. It's helpful to build flexible routines and have recovery time after intense interactions.",
  5: "You exhibit elevated traits that can impact various areas of your life. You may experience noticeable challenges in communication, sensory processing, or adapting to unexpected changes. Support strategies such as planning tools and sensory-friendly environments may provide relief.",
  6: "You show strong alignment with autistic characteristics. Social and sensory fatigue may be common, and disruptions to your routine could lead to stress. You may benefit from a supportive network, structured daily routines, and tools for communication clarity.",
  7: "Your profile indicates very high autistic traits. Navigating daily life may involve substantial effort to manage sensory input, maintain focus, and interact socially. Professional guidance and consistent accommodations may be essential for long-term well-being.",
  8: "You demonstrate extreme alignment with autistic traits. You likely face significant challenges across multiple areas, including communication, sensory regulation, and flexibility. Personalized support, therapeutic interventions, and a structured environment can be crucial in supporting your quality of life.",
};