// src/questions.ts
export const questions = [
  { id: 1, text: "I find maintaining eye contact challenging during conversations.", trait: "social", weight: 1, example: "For example, you may look away or feel pressure when maintaining eye contact." },
  { id: 2, text: "I experience heightened sensitivity to sounds, lights, or textures.", trait: "sensory", weight: 1, example: "For example, you might flinch at sudden sounds or find some clothing uncomfortable." },
  { id: 3, text: "I become distressed when unexpected changes disrupt my routine.", trait: "routine", weight: 1, example: "For example, last-minute cancellations or changes might cause distress." },
  { id: 4, text: "I feel more comfortable communicating through writing than speaking.", trait: "communication", weight: 1, example: "For example, you may prefer emailing or texting instead of phone calls." },
  { id: 5, text: "I can become so focused on a task that I lose track of time.", trait: "focus", weight: 1, example: "For example, you forget to eat or check the time while focused on a task." },
  { id: 6, text: "I feel uneasy or anxious in group conversations.", trait: "social", weight: 1, example: "For example, you avoid talking in group settings due to nerves." },
  { id: 7, text: "Loud or chaotic environments are overwhelming to me.", trait: "sensory", weight: 1, example: "For example, busy shopping centres or noisy events leave you drained." },
  { id: 8, text: "I feel comforted by repeating daily tasks in the same way.", trait: "routine", weight: 1, example: "For example, doing morning routines in the same order each day feels right." },
  { id: 9, text: "I struggle to find the right words in verbal conversations.", trait: "communication", weight: 1, example: "For example, you often pause mid-sentence searching for words." },
  { id: 10, text: "I often focus so intensely on interests that I forget basic needs.", trait: "focus", weight: 1, example: "For example, you might skip meals or lose track of time when focused." },
  { id: 11, text: "Social interactions frequently cause me anxiety.", trait: "social", weight: 1, example: "For example, you feel dread or discomfort before social events." },
  { id: 12, text: "I have strong discomfort toward certain fabrics or clothing tags.", trait: "sensory", weight: 1, example: "For example, tags in clothing might cause irritation or distraction." },
  { id: 13, text: "I strongly prefer to follow fixed schedules and plans.", trait: "routine", weight: 1, example: "For example, you prefer a fixed schedule and avoid unexpected changes." },
  { id: 14, text: "I usually find digital communication easier than in-person conversation.", trait: "communication", weight: 1, example: "For example, texting or emailing feels easier than face-to-face chats." },
  { id: 15, text: "I can focus for extended periods when deeply interested in a topic.", trait: "focus", weight: 1, example: "For example, you can spend hours researching or building something." },
  { id: 16, text: "I often find it difficult to interpret jokes, sarcasm, or implied meanings.", trait: "social", weight: 1, example: "For example, you may take jokes literally or miss sarcasm." },
  { id: 17, text: "Flashing lights or bright lighting can be physically uncomfortable.", trait: "sensory", weight: 1, example: "For example, supermarket lights might hurt your eyes." },
  { id: 18, text: "Interruptions to my routine can lead to significant distress.", trait: "routine", weight: 1, example: "For example, missing a routine task can affect your entire day." },
  { id: 19, text: "I frequently rehearse what I want to say before conversations.", trait: "communication", weight: 1, example: "For example, you mentally script what you want to say before a phone call." },
  { id: 20, text: "I lose track of time easily when I’m focused on something I enjoy.", trait: "focus", weight: 1, example: "For example, you forget appointments or tasks due to deep focus." },
  { id: 21, text: "I find one-on-one interactions easier than group settings.", trait: "social", weight: 1, example: "For example, you prefer one-on-one chats over group discussions." },
  { id: 22, text: "I notice and react strongly to smells others barely detect.", trait: "sensory", weight: 1, example: "For example, smells like perfumes or food bother you more than others." },
  { id: 23, text: "I prefer keeping my personal environment highly organized and predictable.", trait: "routine", weight: 1, example: "For example, you arrange your room or workspace the same way each time." },
  { id: 24, text: "I struggle to read body language or facial expressions.", trait: "communication", weight: 1, example: "For example, you find it difficult to know when someone is annoyed or joking." },
  { id: 25, text: "I become deeply absorbed in topics or activities that interest me.", trait: "focus", weight: 1, example: "For example, you dive into a hobby for hours without noticing." },
  { id: 26, text: "Making eye contact often feels uncomfortable or intrusive.", trait: "social", weight: 1, example: "For example, eye contact feels too intense or overwhelming." },
  { id: 27, text: "Certain repetitive sounds (like humming or tapping) distract or irritate me.", trait: "sensory", weight: 1, example: "For example, someone tapping a pen can be frustrating or unbearable." },
  { id: 28, text: "I rely on consistent routines for meals, sleep, or daily tasks.", trait: "routine", weight: 1, example: "For example, eating breakfast at the same time every day helps you feel in control." },
  { id: 29, text: "I sometimes find it difficult to initiate or sustain conversations.", trait: "communication", weight: 1, example: "For example, starting small talk or keeping a conversation going may feel awkward." },
  { id: 30, text: "I become so engaged in a task that I lose awareness of time passing.", trait: "focus", weight: 1, example: "For example, you forget how long you've been doing something you enjoy." },
  { id: 31, text: "I find it challenging to interpret social cues accurately.", trait: "social", weight: 1, example: "For example, you struggle to know when someone is joking or being serious." },
  { id: 32, text: "I am easily bothered by certain textures or sensations on my skin.", trait: "sensory", weight: 1, example: "For example, you dislike tags, seams, or rough materials." },
  { id: 33, text: "Sudden changes to plans often cause anxiety or stress.", trait: "routine", weight: 1, example: "For example, a change in your schedule might cause panic or confusion." },
  { id: 34, text: "I feel more confident expressing myself through writing.", trait: "communication", weight: 1, example: "For example, you feel more confident explaining yourself in messages than in person." },
  { id: 35, text: "I focus intensely on small details others may overlook.", trait: "focus", weight: 1, example: "For example, you notice pattern details others miss." },
  { id: 36, text: "I avoid social settings because they are mentally exhausting.", trait: "social", weight: 1, example: "For example, after social events, you feel mentally drained or exhausted." },
  { id: 37, text: "I am highly sensitive to temperature changes.", trait: "sensory", weight: 1, example: "For example, a small draft or heat change may be highly noticeable to you." },
  { id: 38, text: "I like following the same path or route during travel.", trait: "routine", weight: 1, example: "For example, you always drive or walk the same route and dislike detours." },
  { id: 39, text: "I have difficulty expressing emotions verbally.", trait: "communication", weight: 1, example: "For example, you struggle to describe your emotions during arguments or discussions." },
  { id: 40, text: "I immerse myself fully in hobbies or projects I care about.", trait: "focus", weight: 1, example: "For example, you can spend hours perfecting a drawing, game mod, or collection." },
];